name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build with cross
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: x86_64-unknown-linux-musl
      
      - name: Install cross
        run: cargo install cross
      
      - name: Build with cross
        run: cross build --target x86_64-unknown-linux-musl --release
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: claudeai-bundle
          path: ./target/x86_64-unknown-linux-musl/release/claudeai-bundle
          if-no-files-found: error
  
  package:
    name: Package as container
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: claudeai-bundle
          path: ./artifact
      
      - name: Make binary executable
        run: chmod +x ./artifact/claudeai-bundle
      
      - name: Extract version
        id: version
        run: |
          VERSION=$(./artifact/claudeai-bundle --version | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.scratch
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/claudeai-bundle:latest
            ghcr.io/${{ github.repository_owner }}/claudeai-bundle:${{ steps.version.outputs.version }}
